import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';


import '@/app/globals.css';
import NextAuthWrapper from "@/library/next.auth.wrapper";
import LayoutWithTopBar from "@/components/layout/LayoutWithTopBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "@hoidanit",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <NextAuthWrapper>
            <div id="app-content-wrapper">
              <LayoutWithTopBar>{children}</LayoutWithTopBar>
            </div>
          </NextAuthWrapper>
        </AntdRegistry>
      </body>
    </html>
  );
}
